### ISSUE TITLE
Ability to edit thumbnails.

### ISSUE THREAD

**Issue by winneon** [Difegue/LANraragi#29] opened 2018-03-03 02:09 UTC
Pretty simple suggestion. Currently, it's impossible to edit thumbnails of existing/uploaded archives. You *could* edit the thumbnail directly in the `thumb` directory that LANraragi generates, but after a few page refreshes, it resets the thumbnail back to the auto-generated image of the first page.

**Comment by Difegue** [comment] 2018-03-03 13:00
I don't plan on supporting custom thumbnails for the moment (I think it's a very edge case), but that thumbnail resetting shouldn't happen. I'll look that up, at least.

**Comment by Difegue** [comment] 2018-03-03 21:19
Can't reproduce on latest version, native Linux. Will try on Docker later.  
If you can still make it happen, please give me a step-by-step reproducible case.

From what I'm seeing, thumbnails will only reset in two ways:  
- Deleting/Renaming the existing file in `thumb`
- Using the `Regenerate Archive Thumbnail` option when opening the archive.

**Comment by winneon** [comment] 2018-03-04 02:22
The test manga I'm using is NSFW content, so I won't link in here.

1. Find an archive that its first image is longer in width than height (say 2 pages in one image).
2. Upload said archive and don't bother editing metadata.
3. Copy a copped version of the first image (cropped so it only has 1 page instead of 2) into the thumbs directory.
4. Delete the old thumb and rename the cropped image to the old thumb's filename.
5. Refresh LANraragi.

Now, if you just refresh or open other pages, the thumbnail will stay, but if you open the archive and then go back to the main page, you'll see that the thumbnail has been regenerated.

**Comment by Difegue** [comment] 2018-03-04 15:30
Yup, there was a bug with the regenerate flag being applied all the time when opening an archive.  
The thumbnail code is a bit old and didn't go through the mojolicious port unscathed.
Couldn't see it earlier due to a second bug with the archives I tested on. (embarassing)  
  
It's all fixed with the above commit, so you should be able to keep custom thumbnails now.  
Thanks again!

**Comment by winneon** [comment] 2018-03-04 18:44
One quick suggestion: could you implement a quick `confirm()` on the regenerate button so if someone like myself were using custom thumbnails and we accidentally pressed the regenerate button, we'd be able to stop the program from overwriting our thumbnails?

**Comment by Difegue** [comment] 2018-03-04 19:02
Sure!

**Closed** 2018-03-09 22:50 UTC
