### ISSUE TITLE
Undefined subroutine Meta data lookup

### ISSUE THREAD

**Issue by Zuescho** [Difegue/LANraragi#57] opened 2018-10-12 14:43 UTC
Hi i just today found your amazing program and after the sad death of HappyPanda this is exactly what i was searching for, i can Import my files but for some reason it keeps failing on importing the meta data.
Could you take a look at this?

**LRR Version and OS**
Docker Version latest, and OS OpenmediaVault 4

**Bug Details**
I seem to not getting any tags for my archives, it just keeps spamming this down below in the logs.
I chose exhentai and nhentai as plugins.

**Matching Logs**
[Shinobu] [error] Undefined subroutine &LANraragi::Model::Plugins::exec_enabled_plugins_on_file called at ./lib/Shinobu.pm line 194.

**Comment by Zuescho** [comment] 2018-10-12 14:59
in case this help, here is the docker itself:
![firefox_2018-10-12_16-57-46](https://user-images.githubusercontent.com/13680959/46876985-fbf1f600-ce3f-11e8-89ae-be0aa29d4338.png)
![firefox_2018-10-12_16-57-56](https://user-images.githubusercontent.com/13680959/46876986-fbf1f600-ce3f-11e8-8cee-d074b1cbcb61.png)
![firefox_2018-10-12_16-58-28](https://user-images.githubusercontent.com/13680959/46877047-217eff80-ce40-11e8-8ddd-3410a4905636.png)
![firefox_2018-10-12_16-58-55](https://user-images.githubusercontent.com/13680959/46877049-22179600-ce40-11e8-85ca-37609d5e89de.png)

**Comment by Difegue** [comment] 2018-10-12 15:31
Looks like the same error that befell #56 - I chalked it up to a bad installation at first but since you're running Docker, it certainly looks like something's wrong with 0.5.4 on new installs and auto-tagging. 

![45ead4ac9cf048c2a93dc583e22734526f6f38fd70e9e2e6d71d4f0c03267979](https://user-images.githubusercontent.com/8237712/46878843-994f2900-ce44-11e8-938d-d77c50b99c5b.jpg)
I'll be right back after some extra testing.

**Comment by Zuescho** [comment] 2018-10-12 18:39
Hi, thanks for the quick respones, just to let you know i dont think it has anything todo with permission because i set everything in there to chmod -R 777 because i thought it would block something.

**Comment by Difegue** [comment] 2018-10-14 13:38
Alright, looks like it was indeed an issue with the Shinobu Background Worker not importing the Plugins package anymore. Must've happened when I refactored the Utils part into multiple files. 

I didn't notice it during testing as I mostly use the built-in upload feature now -- Maybe I should wise up and add more automated testing to deal with regressions like those.  

I'll be pushing an extra hotfix release in the coming hours.

**Comment by Difegue** [comment] 2018-10-14 15:11
Fixed in v.0.5.4-EX.

**Closed by Difegue** 2018-10-14 15:11 UTC
Labels: bug

**Comment by Zuescho** [comment] 2018-10-15 15:12
Hi, thanks for the quick fix. 
Is there any way to force it to get all tags for already importet files? witout pushing the manual button?

**Comment by Difegue** [comment] 2018-10-15 15:28
There used to be one, but I removed it when I did the big jump to Mojolicious a few months ago. I should add an issue to bring it back, considering most of the code for it exists in the oldcgi branch.

A workaround you can use is to trash your database (the dump.rdb) file and let it redetect the archives. If you already did some tagging work and don't want to lose it, you can backup it somewhere, let the new database get tags through autotagging, then use the import/export feature to bring the tags back to your old database.  

Kinda convoluted, but it works! Normally.
