### ISSUE TITLE
Plugin E-Hentai can't download tags match archive.

### ISSUE THREAD

**Issue by huasheng666** [Difegue/LANraragi#688] opened 2022-08-29 10:40 UTC
**LRR Version and OS**
LRR: 0.8.6
OS: Synology Docker

**Bug Details**
E-Hentai v.2.5.1 and Mayriad's EH Master Script v.1.1.1 seems don't work.I tested many comics download from ehentai(did't change filename),but it seems to be unable to fetch external metadata.

**Matching Logs**
EH Master Script v.1.1.1:
[E-Hentai Login] [info] Cookies provided (xx xxx xxxx)!
[Mayriad's EH Master Script] [error] Skipping archive without connecting to EH, because the archive title does not have valid gallery identifiers from Mayriad's EH Master Script.
Error while processing ID xxxx(Skipping archive without connecting to EH, because the archive title does not have valid gallery identifiers from Mayriad's EH Master Script.)

E-Hentai v.2.5.1
Error while processing ID xxxxxxxx (Invalid argument at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 299.
)

I can't figure it out for days,don't know where is the problem.

**Comment by huasheng666** [comment] 2022-09-01 10:09
[E-Hentai] [debug] EH API Tokens are 1726187 / 6538cfj50c
[E-Hentai Login] [info] Cookies provided (xxx xxxx xxxxx)!
[E-Hentai] [info] Reverse Image Search Enabled, trying now.
[E-Hentai] [debug] Using URL https://exhentai.org?advsearch=1&f_sname=on&f_sdt2=on&f_spf=&f_spt=&f_sfu=on&f_sft=on&f_sfl=on&f_shash=84dd41d0a1d1771f407506858479c8ea2806a&fs_covers=1&fs_similar=1&fs_exp=1&f_stags=on (archive thumbnail hash)

it can match the correct archive address,but it can‘t download the tags.

**Comment by alferezkururu966** [comment] 2022-10-07 22:47
I have the same issue, but i want to note that when importing a gallery using the Tsukihi browser plugin it manages to import the tags, but when i add them with the batch operations tab (in order to update the tags) it fails with the same error.
I am also using a synology nas with docker, same lanraragi version and all.

**Comment by Difegue** [comment] 2022-10-08 20:50
Since you're both using Synology devices, I believe this is a duplicate of #656.

See this Github discussion for more information: https://github.com/Difegue/LANraragi/discussions/670

**Closed by Difegue** 2022-10-08 20:50 UTC
