### ISSUE TITLE
Deleted galleries still showing in library until cache is fully rebuilt

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#120] opened 2019-05-05 10:50 UTC
**LRR: 0.59 & 0.60 Beta1
Windows 10
Vagrant 2.2.4**

Whenever I delete a gallery, through LRR the gallery still shows up in LRR's library until I manually rebuild the JSON cache. Or I wait for LRR to finish automatically rebuilding the JSON cache. Both of which take a long amount of time before these ghost galleries disappear from the index.

**Comment by Difegue** [comment] 2019-05-06 19:51
Sounds like inotify not doing its job again; In a way this is pretty close to #122. You running SMB or vbox shared folders?

**Comment by Asinin3** [comment] 2019-05-07 04:14
It happens with both 0.60 b1 and 0.59 so both vbox shared folders and SMB.

**Comment by Asinin3** [comment] 2019-05-14 08:17
This seems to be working actually, at least in the latest nightly. But it's not instant. It will still show in the library for quite some time until LRR decides to do a full rebuild of the JSON Cache. Not sure if I should close the issue because it's definitely quite slow at removing the deleted galleries.

**Comment by Difegue** [comment] 2019-06-03 21:03
Is this still a thing under WSL? I'll be closing this as wontfix if it's a Vagrant-only issue.

**Comment by Asinin3** [comment] 2019-06-03 22:03
Yeah, I just updated the OP a few hours ago to indicate it happens on both Vagrant and WSL.

**Comment by Asinin3** [comment] 2019-06-03 22:05
Yeah deleted galleries still show up on WSL but they do eventually disappear once the json cache finishes rebuilding and you refresh the index. I guess it can be closed if it's not going to get any faster than that, but I'd like to see deleted galleries disappear before the whole cache is rebuilt.

**Comment by Difegue** [comment] 2019-06-04 16:14
Yeah, that much is by design; As long as the cache starts properly rebuilding when archives are deleted it's intended behavior.  

We could modify the json cache by hand to remove deleted keys before doing a full passthrough, but that's a lot of extra code for something people won't likely see often. Tagging under volunteers.

**Comment by Difegue** [comment] 2019-10-09 20:41
With the advent of server-side search, the JSON cache has been annihilated and replaced by a much faster search cache.  

Since it's faster, I have much less qualms about destroying it as soon as data gets out of sync. (Instead of the previous behavior where it'd stick around until the fresh cache was ready)

**Closed by Difegue** 2019-10-09 20:41 UTC
Labels: archive index, enhancement
