### ISSUE TITLE
Windows installer regression in Nightlies (Workaround included)

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#654] opened 2022-07-02 04:22 UTC
As reported in Discord, LANraragi's Windows MSI installer regressed and now gives the following error:
![image](https://user-images.githubusercontent.com/15137035/176986205-8240e081-314a-4459-a546-46850e25598f.png)
This prevents the application from installing properly. However you can close the installer once it's done and go to
`C:\Users\Someone\AppData\Roaming\LANraragi` and run `DistroInstaller.exe` this will fix up the installation.

I'm pretty certain it regressed from one of the commits in this PR https://github.com/Difegue/LANraragi/pull/640

**Comment by Difegue** [comment] 2022-07-02 21:10
I've been aware of this issue for a little while but don't have a clear reproduction state yet! (it doesn't happen on my rig which is annoying). 
I want to fix it for 0.8.6 however so:


* Does this happen on clean installs, upgrades or both?
* Can you get a verbose log through `msiexec` so we can see what the cli command that launches distroinstaller during the installation process looks like? 

Sorry for the annoying questions but help would be much appreciated! 👍

**Comment by Asinin3** [comment] 2022-07-02 23:08
Happens on clean installs, haven't been able to test upgrades as I dont have a newer/older nightly build and the nightly page only has the latest build for download
Log: [LANraragi.txt](https://github.com/Difegue/LANraragi/files/9033826/LANraragi.txt)

**Comment by Difegue** [comment] 2022-07-24 01:25
Been making progress on fixing this -- In the meantime, I've also added a shortcut to run DistroInstaller in case the installation is incomplete, which should help in other fringe distro-not-available scenarios.

![image](https://user-images.githubusercontent.com/8237712/180628154-63ec98dc-1f16-4e0c-ad3c-4d03dfc3da03.png)

**Comment by Difegue** [comment] 2022-07-25 23:53
The installer issue has been fixed as of the latest commit. 🎊

**Closed by Difegue** 2022-07-25 23:53 UTC
Labels: bug, karen-wsl
