### ISSUE TITLE
Can't update a working LANraragi container through docker-ssh and npm deploy

### ISSUE THREAD

**Issue by HunterCop224** [Difegue/LANraragi#16] opened 2018-01-08 09:13 UTC
I downloaded and got LANraragi running right before the 4.0 update and decided to test it out a bit more before updating. I started having an issue with it so I decided to update to 4.0 before raising an issue on that. However since I have a ftp server running on the same machine I cannot connect to the docker ssh to perform the update.

I have FTP software that does not unbind from port 22, and while the issue I have is caused by another program and not LANraragi's fault, I think being able to change the port for updating is essential.

Is there a workaround to this? I am currently trying to copy the docker VHD to another machine to see if I can do the update there.

**Comment by HunterCop224** [comment] 2018-01-08 09:55
I apologize, the message I was getting from FileZilla was one of its internal messages not from the FTP server. On my second computer running Windows 10 Pro I am getting the same error, so this seems to be a LANraragi or Docker issue These are the messages from PowerShell and the Command Prompt.

PowerShell:
```
PS C:\WINDOWS\system32> docker run -e CONTAINER=lanraragi -e AUTH_MECHANISM=noAuth --name lanraragi_ssh -p 2222:22  --rm -v /var/run/d
ocker.sock:/var/run/docker.sock jeroenpeeters/docker-ssh

> docker-ssh@1.0.0 start /usr/src/app
> ./node_modules/forever/bin/forever -c ./node_modules/coffee-script/bin/coffee server.coffee | ./node_modules/bunyan/bin/bunyan

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
[2018-01-08T09:46:50.872Z]  INFO: sshServer/33 on 2b1304c813df: Docker filter
    filter: {
      "name": [
        "^/lanraragi$"
      ]
    }
[2018-01-08T09:46:50.895Z]  INFO: webserver/33 on 2b1304c813df: Listening (host=::, port=8022)
[2018-01-08T09:46:50.896Z]  INFO: sshServer/33 on 2b1304c813df: Docker-SSH ~ Because every container should be accessible
[2018-01-08T09:46:50.896Z]  INFO: sshServer/33 on 2b1304c813df: Listening (host=0.0.0.0, port=22)
```

Command Prompt
```
C:\LANraragi-master>npm run deploy root@localhost:2222:/var/www/lanraragi

> LANraragi@0.4.0 deploy C:\LANraragi-master
> npm install && rsync -e ssh --exclude content -av *  "root@localhost:2222:/var/www/lanraragi"

up to date in 0.118s
ssh: connect to host localhost port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
npm ERR! code ELIFECYCLE
npm ERR! errno 12
npm ERR! LANraragi@0.4.0 deploy: `npm install && rsync -e ssh --exclude content -av *  "root@localhost:2222:/var/www/lanraragi"`
npm ERR! Exit status 12
npm ERR!
npm ERR! Failed at the LANraragi@0.4.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hun\AppData\Roaming\npm-cache\_logs\2018-01-08T09_48_57_283Z-debug.log

C:\LANraragi-master>
```

Both messages are the same on the Windows Server and Windows 10, All antivirus and firewall (including Windows defender and firewall) were disabled before attempting this. All programs were run as administrator.

**Comment by Difegue** [comment] 2018-01-08 18:29
Thanks for the issue report!

After some quick testing, the issue here mostly rests on docker-ssh being a bitch and [not accepting rsyncs](https://github.com/jeroenpeeters/docker-ssh/issues/29). Should've tested this in full before pushing the documentation, so that's my fault.

If you want to update your existing Docker instance to 0.4.0, you can perform the following panic mode hacker commands in powershell to get inside the container and update it manually:

```
docker exec -it lanraragi bash

git clone http://github.com/Difegue/LANraragi.git  
rsync --exclude content -av LANraragi/* /var/www/lanraragi/  
chown -R www-data /var/www/lanraragi/  
chmod -R 755 /var/www/lanraragi/  
```

Now, about solving this issue: 

- The quick 'n easy solution for me is probably to ditch docker-ssh altogether(which is kinda flaky on docker for windows anyways, I've been trying to get a simple ssh session running and it's anything but smooth) and add a ssh server to the container on port 2222.  
There are a few drawbacks to this, notably that I'd have to store dedicated ssh keys/passwords somewhere on the container, and that apparently [tacking sshd in containers is absolute heresy.](https://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/) 

- The better way would be to have people redo their docker instances on every LANraragi update (which would be pretty easy considering we have docker cloud autobuilds now), while keeping all user-generated data (That means archives, image thumbnails and the redis database) inside [a volume.](https://docs.docker.com/engine/admin/volumes/volumes/) That basically means Docker users'd keep their data in a second container, while swapping the webapp container on every update.


I'm planning pretty hefty structural improvements to the app soon™ that will require me to rewrite the Dockerfile anyway, so I'm probably gonna go for number two.

**Comment by HunterCop224** [comment] 2018-01-09 19:30
Option 2 sounds a lot better, and possibly storing all user generated data in a hard drive directory could work too. In this instance I could not do a backup to just start fresh and restore the backup (after adding over 100 archives). Which was the main issue with just wiping the existing docker instance. Ill start working on those emergency hacker commands to see what I can do.

**Comment by Difegue** [comment] 2018-01-09 21:03
If you just want to backup data, you can also try using the database backup/restore feature built-in the LRR web interface. 
It spits out JSON containing all the metadata for added archives.  

Re:Option 2, both docker volumes and hard drive directories(basic bind mounts) can be possible, as that depends on the mapping the user applies when building his container instance.

**Comment by HunterCop224** [comment] 2018-01-09 21:08
I apologize, I forgot to mention that the problem I was having was that I was getting (on the version right before 4.0.0) ERR_EMPTY_RESPONSE pages from LANraragi, going to a different page then hitting the back button would load the page properly but I could never download the backup. I wanted to update to the latest version before reporting it as an issue.

**Comment by Difegue** [comment] 2018-01-09 21:14
Oh shit, that changes everything - didn't think your problem was related to the backup/restore page.

If you still find it in 0.4.0, please open a second issue. 
( ERR_EMPTY_RESPONSE is a chrome-specific error, but it basically means the server never returned the JSON -- maybe the backup process hangs somewhere and times out? )

**Comment by HunterCop224** [comment] 2018-01-09 21:31
I was getting it in Chrome and Vivaldi (which is based on the Chrome rendering engine) its not specific to any page, but it renders the backup/restore function inoperable. I'd get it when just going to "localhost:8080/lanraragi" or any of the settings links at the top of the page. I would get this error immediately when loading a page. The backup/restore would just give me a blank page after clicking the backup button and not do anything. Hopefully it gets fixed with the update so I can at least do a backup. I have been running LANraragi since its first install and it only started doing that after there was a power outage and I had to do "docker start lanraragi" to get it going again.

If the issue still pertains i'll open a second ticket, there's a lot of strange things going on and different parts of LANraragi behave differently. Some pages load by me going somewhere else then hitting the back button, other pages (gallery's in specific) just never load no matter what I try. Ill try and make a webm screen record or something as that might explain it the best.

I also tried Internet Explorer which just never loaded. And FireFox on a different computer which just said no response.

**Comment by HunterCop224** [comment] 2018-01-10 04:38
Ok so The version I was _on_ was "0.3.8". Updating it to 0.4.0 with the steps shown above wiped its database and now doesn't show any archives, but still remembers the password I set for admin. I have two things to report. 

On the install that held all of my database information. Everything seemed to work fine (even though I didn't think to to a database backup anyway) until I told docker to stop and start lanraragi. After that I would at first get a ERR_EMPTY_RESPONSE but after doing the trick to load the page I got an Apache error stating the resource was busy or not avalible.

So I wiped the entire lanraragi container and started anew, I have a backup of dockers virtual hard drive from when this issue happened so no sweat. However I noticed that it downloaded and installed 0.3.8 which I went and upgraded to 0.4.0 using your above method. Everything worked perfectly (I did not test galleries though) And I was able to download a database backup from this fresh install. Even after restarting through docker I am having no issues with loading pages now.

So I think that its possible that when the power here was cut the docker container may have been corrupted or damaged causing these issues I'm having. Ill see if windows backup somehow has a copy of the docker container file I can restore to and see if the issue persists before the power outage happened. As said I do have the docker VHDX from when this started happening as backup. Is there anyway to backup the lanraragi database from that without being able to access the database backup page?

**Comment by Difegue** [comment] 2018-01-10 15:37
Yeah, your comment made me think of a container corruption caused by the power outage -- Sounds like I was right. 

Backuping the database should be possible by copying the redis database file and pasting it in your fresh install. It should be in /var/lib/redis/ as a .rdb file.

**Comment by Difegue** [comment] 2018-01-23 15:08
With the upcoming v.0.4.5, the setup procedure has been entirely overhauled (been a long time coming), alongside a brand-new Dockerfile. (1b3cf00)  

As discussed in the above comments, all user data is now confined to the ./content directory for Docker builds (Redis DB, archives and archive thumbnails). 
By mapping this directory to either a Docker volume or a basic directory on their OS, users can therefore simply destroy and rebuild their container to update cleanly. 

The mojolicious branch isn't merged yet (still needs documentation and a bit more testing), but once it is, Docker cloud should start autobuilding ready-to-use container images.

**Closed by Difegue** 2018-01-23 15:08 UTC
