### ISSUE TITLE
[Bug] Different files are considered the same file in the system

### ISSUE THREAD

**Issue by SiIentZephyrus** [Difegue/LANraragi#365] opened 2020-11-21 11:52 UTC
Although there are 89 files in the statistical options, the actual list is only 82.Then I discovered that there were only 3 comics in 10 series. I deleted 10 files and added files manually, but when I uploaded the first one without any problems, an error occurred when uploading the second one. The error is that the uploaded file has already appeared in the current database.The reason for the error is that the same file already exists in the database, and the last comic I uploaded is displayed in the edit metadata. I want to ask why this is.

**Comment by Difegue** [comment] 2020-11-21 13:57
How did you add/delete the files?
Deleting from the metadata edit page wipes the database entry, but deleting files directly from the filesystem doesn't drop them from the database in order to prevent accidental data loss.

You can use the clean database button in settings if you want to remove said entries.

**Comment by SiIentZephyrus** [comment] 2020-11-22 05:08
There is no problem with deleting. The problem is that the number of files displayed in the statistics menu at the top of the page is inconsistent with the number of files I see in the list. The statistics show that there are 89 files, but only 82 can be seen in the list. I found 7 zip archives that were not found by the system.

**Comment by Difegue** [comment] 2020-11-24 20:51
The count at the top always shows the full number of entries in the database, but the list has a built-in filter to hide entries that don't have a filesystem entry.  

As said earlier, you can use the clean DB feature to remove those extra/rogue entries and everything should be fine:  
![image](https://user-images.githubusercontent.com/8237712/100149672-d8169080-2e9e-11eb-897e-6d7797519d5e.png)  

By re-reading your first post, there might indeed be an issue with the new uploader if you try to upload a file after having deleted it from the FS but not from the database -- I'll have to check to make sure.

**Comment by SiIentZephyrus** [comment] 2020-11-25 05:05
The files not shown in the list actually exist, and I can find them in the file directory. So I wonder why the statistics show the correct number, but the list does not recognize it. I wonder if it is because of the md5 verification of the file. The recognizer treats two different files as the same file.

**Comment by Difegue** [comment] 2020-11-26 20:37
Oh, I didn't understand the issue that way, sorry.  

Could you provide me with two files that are treated as the same ?  
The hashing algorithm is usually pretty good and never gave me dupe issues(well unless the files **are** identical), but there's a first time for everything.

**Comment by SiIentZephyrus** [comment] 2020-11-27 12:20
https://mega.nz/folder/ln4gFBjA#RVxmjYsw6Tqp3tXnhEb6OQ
Of the ten files in the network disk, my system can only recognize three, and the rest are regarded as duplicate files.

**Comment by Difegue** [comment] 2020-11-28 16:47
I reproduced the problem, although I don't think I can fix it easily on this side. It is indeed a problem with the hash verification.  
The LRR hashing algorithm takes the first 512KBs of a file, and computes the SHA-1 hash of those 512KBs to provide the ID.  
(The entire file isn't used in order to make ID calculation fast, basically)

In the case of your 10 files, they all start with the exact same 1265KB image (CRC: A7CED445).  
Zip is a simple file format, so the beginning of the file is essentially this image.  
As such, the archives aren't different enough at the beginning for the algorithm to assign them a different ID...

A few simple, albeit not very satisfying solutions on your side would be:  

* Remove said first image from the chapters to make them all distinct enough
* Merge all 10 chapters into one file
* Change the format from zip to something that introduces a checksum at the beginning of the file. **7z** works perfectly fine in this scenario:  
![image](https://user-images.githubusercontent.com/8237712/100520887-a7856e00-31a0-11eb-86e6-ecab1b67ec9a.png)  

The true solution would be for me to rework the hashing algorithm so it takes in more data, but this is very much an edge case, and changing the way IDs are generated at this point would basically break **everything** for existing users without a bunch of extra migration code.

So uh I guess this is a wontfix for now? Let me know if you have any extra ideas, but considering this is the first time this issue propped up in 5 years I don't think it warrants putting in large efforts to fix it. Sorry!

**Comment by SiIentZephyrus** [comment] 2020-11-29 03:10
Well, thank you for your answer!

**Closed** 2020-11-29 19:45 UTC
Labels: archive index, bug, wontfix

**Comment by brachna** [comment] 2023-11-08 01:50
It sure would be nice to increase search from 512KBs, I'm encountering this issue now and again because translations use same cover image. Re-archiving into 7z fixes this, but the process is slow.
