### ISSUE TITLE
EHMasterScript Import Tagging Fails

### ISSUE THREAD

**Issue by WorstGirl** [Difegue/LANraragi#536] opened 2021-11-13 02:10 UTC
**LRR Version and OS**
LRR 0.8.1, Docker, Ubuntu 20.04LTS

**Bug Details**
EHMasterScript auto-tagging fails on 0.8.1, worked fine on 0.8.0. Tagging the gallery manually using the Ex URL works, it just fails during tag on import.

**Matching Logs**
LRR Logs:
```
[2021-11-13 02:03:10] [Auto-Plugin] [info] Executing enabled metadata plugins on archive with id c931d8aab3eec779b4e763843d14b9555d308724.
[2021-11-13 02:03:10] [Plugin System] [info] Thumbnail hash invalid, regenerating.
[2021-11-13 02:03:12] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 02:03:12] [Plugin System] [info] Applying tag rules...
[2021-11-13 02:03:12] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 02:03:12] [Auto-Plugin] [error] Can't locate object method "post" via package "2002633" (perhaps you forgot to load "2002633"?) at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 288.
```

Plugin Logs:
```
[2021-11-13 02:03:12] [Date Added Plugin] [info] Using file date
[2021-11-13 02:03:12] [Mayriad's EH Master Script] [info] Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API.
```

![6syhqq](https://user-images.githubusercontent.com/37132854/141601970-f5cb1163-7149-4ba8-8c1d-fb16fac524e7.jpg)

**Comment by Difegue** [comment] 2021-11-13 19:24
There have been no changes to the EH-related scripts in 0.8.1, so I'm guessing the issue is with this archive in particular.  
Do you get more info by turning on Debug mode?

**Comment by WorstGirl** [comment] 2021-11-13 23:46
I tried five random archives, all had the same result.
Three were freshly downloaded from random galleries.
Two were already in the database before I removed them (They were imported successfully using EHMasterScript previously).

![lwqasb](https://user-images.githubusercontent.com/37132854/141662174-5fb846f9-9f2d-46c6-8fb7-3b0b38fe5a6b.jpg)

This error is present in the docker container output only, one time for each archive.
`lanraragi_server.1.yu8qxv0x3vak@Tomoyo    | Use of uninitialized value $plugin_result{"new_tags"} in split at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Plugins.pm line 64.`

Here are the logs (with debug mode on)

LRR:
```
[2021-11-13 23:31:05] [Search Engine] [debug] Search request: --title-0--
[2021-11-13 23:31:05] [Search Engine] [debug] Using cache for this query.
[2021-11-13 23:31:39] [File Upload/Download] [debug] ID of uploaded file is ed9513f558d4fca769072fbca1cca13fe4308fac
[2021-11-13 23:31:39] [Archive] [debug] Pushing to redis on ID ed9513f558d4fca769072fbca1cca13fe4308fac:
[2021-11-13 23:31:39] [Archive] [debug] File Name: [Death2cu] New life [English] [GID 2059727 GT 6173012968]
[2021-11-13 23:31:39] [Archive] [debug] Filesystem Path: /home/koyomi/lanraragi/content/[Death2cu] New life [English] [GID 2059727 GT 6173012968].zip
[2021-11-13 23:31:39] [File Upload/Download] [debug] ID of uploaded file is 0672b23416a12ecd0a95a03ad138a869e90e4709
[2021-11-13 23:31:39] [File Upload/Download] [debug] ID of uploaded file is b1a2bc6dd69b3dec896f1ea66592267232275f6c
[2021-11-13 23:31:39] [Archive] [debug] Pushing to redis on ID 0672b23416a12ecd0a95a03ad138a869e90e4709:
[2021-11-13 23:31:39] [Archive] [debug] File Name: [Fuyuichi Monme] Amayakashi Jouzu no Nagasato-san Ã¯Â½Å¾ Hokenshitsu de Yoshi Yoshi Ecchi!Ã¯Â½Å¾ Ch. 3 [English] [GID 2059733 GT effc05e24e]
[2021-11-13 23:31:39] [Archive] [debug] Filesystem Path: /home/koyomi/lanraragi/content/[Fuyuichi Monme] Amayakashi Jouzu no Nagasato-san Ã¯Â½Å¾ Hokenshitsu de Yoshi Yoshi Ecchi!Ã¯Â½Å¾ Ch. 3 [English] [GID 2059733 GT effc05e24e].zip
[2021-11-13 23:31:39] [Archive] [debug] Pushing to redis on ID b1a2bc6dd69b3dec896f1ea66592267232275f6c:
[2021-11-13 23:31:39] [Archive] [debug] File Name: (Bokura no Love Live! 31) [Erostellus (Miel)] Over Connect (Love Live! Nijigasaki High School Idol Club) [GID 2059457 GT 6f86eaf9aa]
[2021-11-13 23:31:39] [Archive] [debug] Filesystem Path: /home/koyomi/lanraragi/content/(Bokura no Love Live! 31) [Erostellus (Miel)] Over Connect (Love Live! Nijigasaki High School Idol Club) [GID 2059457 GT 6f86eaf9aa].zip
[2021-11-13 23:31:39] [File Upload/Download] [debug] Running autoplugin on newly uploaded file ed9513f558d4fca769072fbca1cca13fe4308fac...
[2021-11-13 23:31:39] [Auto-Plugin] [info] Executing enabled metadata plugins on archive with id ed9513f558d4fca769072fbca1cca13fe4308fac.
[2021-11-13 23:31:39] [Plugin System] [info] Thumbnail hash invalid, regenerating.
[2021-11-13 23:31:40] [File Upload/Download] [debug] Running autoplugin on newly uploaded file 0672b23416a12ecd0a95a03ad138a869e90e4709...
[2021-11-13 23:31:40] [Auto-Plugin] [info] Executing enabled metadata plugins on archive with id 0672b23416a12ecd0a95a03ad138a869e90e4709.
[2021-11-13 23:31:40] [Plugin System] [info] Thumbnail hash invalid, regenerating.
[2021-11-13 23:31:40] [File Upload/Download] [debug] ID of uploaded file is cc80b766146e2c9fdbb1e52d617f047bc0e847e2
[2021-11-13 23:31:40] [Archive] [debug] Pushing to redis on ID cc80b766146e2c9fdbb1e52d617f047bc0e847e2:
[2021-11-13 23:31:40] [Archive] [debug] File Name: [moheji] Sister to Succubus 6 [GID 2059574 GT 16660469fb]
[2021-11-13 23:31:40] [Archive] [debug] Filesystem Path: /home/koyomi/lanraragi/content/[moheji] Sister to Succubus 6 [GID 2059574 GT 16660469fb].zip
[2021-11-13 23:31:40] [File Upload/Download] [debug] Running autoplugin on newly uploaded file b1a2bc6dd69b3dec896f1ea66592267232275f6c...
[2021-11-13 23:31:40] [Auto-Plugin] [info] Executing enabled metadata plugins on archive with id b1a2bc6dd69b3dec896f1ea66592267232275f6c.
[2021-11-13 23:31:40] [Plugin System] [info] Thumbnail hash invalid, regenerating.
[2021-11-13 23:31:40] [File Upload/Download] [debug] ID of uploaded file is c62c8d3f6f64cd86de69c27b49aaf95683696023
[2021-11-13 23:31:40] [Archive] [debug] Pushing to redis on ID c62c8d3f6f64cd86de69c27b49aaf95683696023:
[2021-11-13 23:31:40] [Archive] [debug] File Name: [SEVEN TAILS (Fukuinu)] KARIN Archive (Blue Archive) [English] =White Symphony= [GID 2059671 GT cc73717281]
[2021-11-13 23:31:40] [Archive] [debug] Filesystem Path: /home/koyomi/lanraragi/content/[SEVEN TAILS (Fukuinu)] KARIN Archive (Blue Archive) [English] =White Symphony= [GID 2059671 GT cc73717281].zip
[2021-11-13 23:31:41] [File Upload/Download] [debug] Running autoplugin on newly uploaded file cc80b766146e2c9fdbb1e52d617f047bc0e847e2...
[2021-11-13 23:31:41] [Auto-Plugin] [info] Executing enabled metadata plugins on archive with id cc80b766146e2c9fdbb1e52d617f047bc0e847e2.
[2021-11-13 23:31:41] [Plugin System] [info] Thumbnail hash invalid, regenerating.
[2021-11-13 23:31:41] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:41] [Plugin System] [info] Applying tag rules...
[2021-11-13 23:31:41] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:41] [Auto-Plugin] [error] Can't locate object method "post" via package "2059733" (perhaps you forgot to load "2059733"?) at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 288.
[2021-11-13 23:31:41] [File Upload/Download] [debug] Running autoplugin on newly uploaded file c62c8d3f6f64cd86de69c27b49aaf95683696023...
[2021-11-13 23:31:41] [Auto-Plugin] [info] Executing enabled metadata plugins on archive with id c62c8d3f6f64cd86de69c27b49aaf95683696023.
[2021-11-13 23:31:41] [Plugin System] [info] Thumbnail hash invalid, regenerating.
[2021-11-13 23:31:42] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:42] [Plugin System] [info] Applying tag rules...
[2021-11-13 23:31:42] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:42] [Plugin System] [info] Applying tag rules...
[2021-11-13 23:31:42] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:42] [Auto-Plugin] [error] Can't locate object method "post" via package "2059574" (perhaps you forgot to load "2059574"?) at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 288.
[2021-11-13 23:31:42] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:42] [Auto-Plugin] [error] Can't locate object method "post" via package "2059727" (perhaps you forgot to load "2059727"?) at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 288.
[2021-11-13 23:31:42] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:42] [Plugin System] [info] Applying tag rules...
[2021-11-13 23:31:42] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:42] [Auto-Plugin] [error] Can't locate object method "post" via package "2059457" (perhaps you forgot to load "2059457"?) at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 288.
[2021-11-13 23:31:43] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:43] [Plugin System] [info] Applying tag rules...
[2021-11-13 23:31:43] [Plugin System] [info] No login plugin specified, returning empty UserAgent.
[2021-11-13 23:31:43] [Auto-Plugin] [error] Can't locate object method "post" via package "2059671" (perhaps you forgot to load "2059671"?) at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 288.
```

Plugin:
```
[2021-11-13 23:31:41] [Date Added Plugin] [debug] Processing file: /home/koyomi/lanraragi/content/[Fuyuichi Monme] Amayakashi Jouzu no Nagasato-san Ã¯Â½Å¾ Hokenshitsu de Yoshi Yoshi Ecchi!Ã¯Â½Å¾ Ch. 3 [English] [GID 2059733 GT effc05e24e].zip
[2021-11-13 23:31:41] [Date Added Plugin] [info] Using file date
[2021-11-13 23:31:41] [Mayriad's EH Master Script] [info] Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API.
[2021-11-13 23:31:42] [Date Added Plugin] [debug] Processing file: /home/koyomi/lanraragi/content/[moheji] Sister to Succubus 6 [GID 2059574 GT 16660469fb].zip
[2021-11-13 23:31:42] [Date Added Plugin] [info] Using file date
[2021-11-13 23:31:42] [Date Added Plugin] [debug] Processing file: /home/koyomi/lanraragi/content/[Death2cu] New life [English] [GID 2059727 GT 6173012968].zip
[2021-11-13 23:31:42] [Date Added Plugin] [info] Using file date
[2021-11-13 23:31:42] [Mayriad's EH Master Script] [info] Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API.
[2021-11-13 23:31:42] [Mayriad's EH Master Script] [info] Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API.
[2021-11-13 23:31:42] [Date Added Plugin] [debug] Processing file: /home/koyomi/lanraragi/content/(Bokura no Love Live! 31) [Erostellus (Miel)] Over Connect (Love Live! Nijigasaki High School Idol Club) [GID 2059457 GT 6f86eaf9aa].zip
[2021-11-13 23:31:42] [Date Added Plugin] [info] Using file date
[2021-11-13 23:31:42] [Mayriad's EH Master Script] [info] Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API.
[2021-11-13 23:31:43] [Date Added Plugin] [debug] Processing file: /home/koyomi/lanraragi/content/[SEVEN TAILS (Fukuinu)] KARIN Archive (Blue Archive) [English] =White Symphony= [GID 2059671 GT cc73717281].zip
[2021-11-13 23:31:43] [Date Added Plugin] [info] Using file date
[2021-11-13 23:31:43] [Mayriad's EH Master Script] [info] Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API.
```

**Comment by Difegue** [comment] 2021-11-26 13:34
MEMS plugin hadn't been updated to match the new function signature in the E-H plugin, should be fixed now.

**Closed by Difegue** 2021-11-26 13:34 UTC
