### ISSUE TITLE
Add multiple matching lists to a single dynamic category

### ISSUE THREAD

**Issue by myzzh5** [Difegue/LANraragi#1093] opened 2024-10-11 11:53 UTC
**Please describe your suggestion, and the problem it'd solve.**
I feel frustrated that a single dynamic category can only match one tag now.
I want to match a single dynamic category with multiple tags, for example, if my dynamic list name is Youth, and I added "Love", "Teenage", "Healing", "Passion" and so on in Predicte, and my file tag matches one of the above, the file will be automatically added to the Youth dynamic category.
In this way, everyone can add and edit their own dynamic tags according to their preferences, making LRR more personalized and faster in filtering the files they like to watch.
Just like below.

![492fe193-c5e9-4cdf-bfa9-16d031e06e1a](https://github.com/user-attachments/assets/cfa68fc3-d98e-42c4-8922-9be8438d9050)

**Comment by Difegue** [comment] 2024-10-12 01:26
I believe this is at its core a duplicate of https://github.com/Difegue/LANraragi/issues/754 - Having OR searches would allow you to have dynamic categories with multiple tags.  

I'll close this but will keep tracking on that issue above. Thanks for the inquiry!

**Closed by Difegue** 2024-10-12 01:26 UTC
Labels: duplicate
