### ISSUE TITLE
Using an encrypted drive as the WSL content folder causes crashes

### ISSUE THREAD

**Issue by izgtbvdb** [Difegue/LANraragi#182] opened 2019-08-31 15:06 UTC
v.0.6.0 Beta 2 -- Moss Garden, Windows installer / Windows 10

Been using LANraragi for the first time over the past couple of days and am really liking it, except for a couple of problems I'm having making it unusable. Right now I am just using it with a local folder with a couple of archives as a test.

1) Everything seems to be running nicely for a while, but eventually, I appear to get disconnected, and my browser will just load forever when attempting to navigate anywhere. While typing this, it took about 15 minutes for it to go down. Sometimes stopping the server and starting it again will let me back in, but usually not. I need to restart the program, which leads to...

2) After closing the program, I can't usually open it again. Task Manager shows the "LANraragi for Windows" process is running. I can end that task, but it doesn't help. I also see two "perl" processes running, which resfuse to close. There might be more processes I don't know about. 
So far the only way I can get the program running again is by restarting Windows.

3) I get the following error when attemping to load tags with the E-Hentai plugin

> Error :
> Connect timeout at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/EHentai.pm line 158.

I have configured the plugin with my ehentai id/password.  If I enter the gallery URL in the box provided, it works just fine and populates the tags. Other plugins such as the nHentai work without the gallery URL.

**Comment by Difegue** [comment] 2019-08-31 15:53
1. Sounds like the server crashes after 15 or so minutes on your end. It's a bit unusual; You might try enabling debug mode and stop/start the server to see if you get anything weird in the Console Log.

2. The frozen perl processes are the issue here. You can force-close them in Task Manager if you use the "Detail" tab, at which point LRR for Windows should allow you to start them again.

3. Beta 2's E-Hentai code is a bit outdated since the whole exhentai closing debacle happened -- I have a newer version in the nightlies which I'll be releasing soon. The gallery URL part uses the API directly and doesn't require a login, so it's no surprise that those'd work.

**Comment by CirnoT** [comment] 2019-08-31 22:48
Regarding EH issue, seems like connection timeouts to e-hentai. Their site been slow lately but I never encountered any issues myself. Possibly issue with your internet connection?

**Comment by izgtbvdb** [comment] 2019-09-01 05:14
I had already been running debug mode and watching both the console log and application logs show nothing of note.

This time the server stayed up for about 7 minutes before dropping. I'm going to try installing on another machine to see if there is any difference there.

Generally my internet connection is decent enough, though I often do have trouble with exhentai not loading pages..  In any case, should that even matter since it is running locally?

Regarding the frozen processes, I am still completely unable to end them. Wether it's from the Details tab in Task Manager, or even using taskkill from cmd prompt (yes, I ran it as admin). I also note this time there were no perl processes, but instead I got 1 python2.7 process.

> C:\Windows\system32>taskkill /F /PID 10380
> ERROR: The process with PID 10380 could not be terminated.
> Reason: Access is denied.

Also worth noting is from what I can see, as long as I havn't yet had the disconnect, I can close and reopen the program just fine, with no stuck processes, but as soon as I get that disconnect it all goes to shit.

**Comment by izgtbvdb** [comment] 2019-09-01 12:10
OK, so bit of an update. I installed on another machine which had been freshly formatted with Windows 10. I had not yet connected it to the internet, so tried running LANraragi offline to see what would happen. Let it run for a while, and got no disconnects.

Once I went online though it didn't take long for it to go down.

However, this time I got something which I didn't se before - a Mojolicious-themed page with some actual error messages:

> 162 | # Icky backwards compatibility wrapper. :-(
> -- | --
> 163 | local @CARP_NOT = $cgc ? $cgc->() : caller();
> 164 | shortmess_heavy(@_);
> 165 | }
> 166 |  
> 167 | sub croak   { die shortmess @_ }
> 168 | sub confess { die longmess @_ }
> 169 | sub carp    { warn shortmess @_ }
> 170 | sub cluck   { warn longmess @_ }
> 171 |  
> 172 | BEGIN {

![mojo1](https://user-images.githubusercontent.com/50206297/64076173-8328b080-cd15-11e9-8762-c2fa584e54a9.JPG)
![mojo2](https://user-images.githubusercontent.com/50206297/64076174-8328b080-cd15-11e9-98e7-7610b0860445.JPG)


> [2019-09-01 11:21:20.14766] [14] [debug] Template "not_found.development.html.tt2" not found
> --
> [2019-09-01 11:21:20.14940] [14] [debug] Template "not_found.html.tt2" not found
> [2019-09-01 11:21:20.15126] [14] [debug] Rendering cached template "mojo/debug.html.ep"
> [2019-09-01 11:21:20.16368] [14] [debug] 404 Not Found (0.017902s, 55.860/s)
> [2019-09-01 11:21:21.25556] [14] [debug] GET "/" (f26b1c9a)
> [2019-09-01 11:21:21.25578] [14] [debug] Routing to controller "LANraragi::Controller::Index" and action "index"
> [2019-09-01 11:21:24.25676] [14] [error] Could not connect to Redis server at 127.0.0.1:6379: Address in use at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Config.pm line 38.
> [2019-09-01 11:21:24.25712] [14] [debug] Template "exception.development.html.tt2" not found
> [2019-09-01 11:21:24.25740] [14] [debug] Template "exception.html.tt2" not found
> [2019-09-01 11:21:24.25756] [14] [debug] Rendering cached template "mojo/debug.html.ep"

I went away for about 30 minutes and when I returned, found it was working again, without me ever stopping or restarting...

**Comment by Difegue** [comment] 2019-09-01 16:33
There's not a single trace of python in what I ship normally, so that process must've come from somewhere else.  

As for those logs...that Redis connection issue has happened a few times with other Windows users, but it's so intermittent I have no idea what's causing the issue. It's likely related to WSL itself and might be fixed in a subsequent Windows release.

**Comment by CirnoT** [comment] 2019-09-01 20:13
Reporting on E-Hentai plugin issue - using new version of plugin should solve that. Old version used sadpanda without SSL and that seems to be disabled now (server does not respond on port 80)

**Comment by izgtbvdb** [comment] 2019-09-02 07:26
If there's any kind of testing I can do to give you more information on the problem, let me know.

Regaring the E-Hentai plugin - I found the new version had just been released while I was doing my testing and writing my last reply, so I didn't test it a whole lot.

I'm going by memory here, but what I found was it connected fine the first few times, but was pulling tags from the wrong gallery. The gallery in question had the same title, but different author/series/circle/everything else. After a while, I started getting the connection errors again.

I only tried the one gallery, so this needs some more testing.

**Comment by Difegue** [comment] 2019-09-02 09:30
You might want to try with the latest Windows Insider release of Win10.

**Comment by izgtbvdb** [comment] 2019-09-03 02:35
I'll take a look at that on my test machine.
I might also be able to test the program in another location on a different network.

In the mean time, I want to try and diagnose the connection problem myself if I can. I'm not very savvy with webservers and stuff, and probably don't know quite how this program actually works. What exactly should I be looking for, or what should I be Googling?

On the bright side, the E-Hentai plugin is working now. Turns out that was my dumb fault as I hadn't enabled the ex-Hentai option, and I guess the couple of test galleries I were using could not be found on regular e-Hentai. I added a bunch more galleries and everything was working beautifuly for a while until it eventually disconnected.

**Comment by Difegue** [comment] 2019-09-03 08:58
Oh right, supervisord is python 2.4. Sorry about that.

**Comment by izgtbvdb** [comment] 2019-09-03 09:51
Just tried running wsl.exe on my PC which currently has the frozen processes, and it was unresponsive. I cannot even run wsl.exe, so it seems WSL is crashing entirely? On my other machine which I haven't given a chance to crash yet, the above command clears all the LANraragi processes as expected.

**Comment by izgtbvdb** [comment] 2019-09-05 07:28
OK, so I installed on another PC on another network and had it running all day. It worked perfectly and wouldn't crash no matter what I did to it. Same version of LANraragi and same version of Windows. No settings were ever changed on either installation as far as networks go.

Now I'm just completely stumped. It's now been tested in 2 different PCs on my home network and crashes on both.

Really hope someone can come up with something as I don't think using it only at work is going to be an option.

**Comment by Difegue** [comment] 2019-09-05 09:50
You can try generating detailed WSL logs following [the instructions here](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs), but I don't think they'll help much sadly.  

If you installed a Win10 Insider Preview you can also try using WSL2: 
https://www.pengwin.dev/blog/2019/6/12/enable-wsl2-and-convert-existing-pengwin-installations 
`wsl --set-version lanraragi 2`

**Comment by izgtbvdb** [comment] 2019-09-10 12:47
It seems like I run into trouble when using a folder on an encrypted drive as my content folder. I had been doing this on my main PC, and after changing it to another drive, I have not had any trouble, even with me trying my hardest to make it crash.

To test this I set up my test PC (which had been running LANraragi fine) with a similar encrypted drive setup, and it started crashing again. Right now I've got it set back to a regular drive again and it hasn't crashed yet.

I can't say for sure if this is the cause of the problem here as I'm pretty sure I have encountered the crashing on both machines on regular drives. More testing required...

**Comment by Difegue** [comment] 2019-09-17 21:46
Which method do you use to encrypt the drive? I might try reproducing this with a spare usb drive or something.

**Comment by Difegue** [comment] 2019-09-18 16:18
> 17:28:17 ***** i can reproduce this if i force LRR to save to a volume thats mounted by veracrypt                                                17:28:28 ***** seems to be an issue with WSL trying to access such volumes                  
17:29:03 ***** in fact it crashed when trying to upload test archive      
17:30:00 ***** it crashes whole WSL layer 
17:35:46 ***** perl processes are stuck in Wait:WrPushLock  

Doesn't seem like this is fixable by me as it's a WSL issue. Closing as wontfix.

**Closed by Difegue** 2019-09-18 16:18 UTC
Labels: bug, karen-wsl, wontfix

**Comment by izgtbvdb** [comment] 2019-09-23 12:16
I see this is closed now, but just to let you know - Yes, I was using it with a content folder on a VeraCrypt encryped drive.
Since changing the content folder to a regular drive a couple of weeks ago, I have had not encountered any issues at all.

**Comment by Difegue** [comment] 2019-09-23 12:22
This is supposedly a thing that only happens with VeraCrypt, Bitlocker and al. aren't affected.  
I should probably add a warning in the documentation for this.
