### ISSUE TITLE
Search results mismatch and untagged returns random stuff.

### ISSUE THREAD

**Issue by Guerra24** [Difegue/LANraragi#501] opened 2021-09-04 08:26 UTC
**LRR Version and OS**
Nightly, Docker and Debian 11 host.

**Bug Details**
While adding new archives I noticed that a plugin broke and the only way to stop it ofc is to shutdown the instance, then while off I moved only those archives out. Started up again, ran cleanup and successfully remove those entries. Then moved back in the archives and restarted the instance. This caused search to return the classic `3,463 ancient chinese lithographies. (filtered from 3,494 total entries)`.

Clean search cache and a clean db later... nothing. This also had the side effect of making `untagged only` return random archives. Adding or removing archives causes untagged to return a different *set* of archives, always the same amount. Combining untagged and new only also returns random archives. 

![image](https://user-images.githubusercontent.com/9023392/132087194-e52a7bcd-1145-4c39-8f85-e55f161c909e.png)

I had fixed this by moving stuff around while running but since that is also kinda broken I can't do that. Regardless it shouldn't break this bad at all.

This is different from #282 and #376 since everything got added correctly and untagged being completely f-up.

<sub><sub>just @ me on discord, making this issue because it's quite long</sub></sub>

**Comment by Guerra24** [comment] 2021-09-05 17:58
Rolling back to 0.7.9 gets rid of the issue but the damage still there since upgrade to nightly brings it back. 🤔

**Comment by Difegue** [comment] 2021-09-05 20:40
Good to know, this might be caused by the recent changes to search. I'll try investigating this when time allows.

**Comment by Difegue** [comment] 2021-09-25 13:51
Untagged search was busted due to moving search to an atomic redis operation, should be fixed now.

**Closed by Difegue** 2021-09-25 13:51 UTC
