### ISSUE TITLE
Archive with nested folders

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#2] opened 2017-12-09 21:02 UTC
Hello.
Any archives added that have nested folders will cause LANraragi to stop working after the upload is complete and return to library is clicked. Library works after deleting the file.

**Comment by Difegue** [comment] 2017-12-09 21:05
I had seen this a few times, but chalked it up to corrupt archives. 
This might be a good opportunity to rework the way we unzip stuff...Gonna look into it.

**Comment by Difegue** [comment] 2017-12-10 13:31
After rapid testing, it doesn't look like this comes from nested folders.  
Shouldve kept my own bugged archives to see what causes this back then. 

Do you have an archive causing the issue I could use as a reproducible case?

**Comment by xd1986k** [comment] 2017-12-10 16:57
[Here's](http://bit.ly/2yVBIjh) the file in question.

**Comment by Difegue** [comment] 2017-12-10 18:15
Turns out this came from the "–" character in the filename.
Another issue with unicode handling - never gonna see the end of that shit.

Fixed by [commit n°167.](https://github.com/Difegue/LANraragi/commit/86d27f1719fd85720691a3b4a3bb6f7c1cbce4ef) 
I'll push a release soon, but you can hotpatch the functions_index.pl file in the meantime.

**Closed by Difegue** 2017-12-10 18:15 UTC
Labels: bug
